#!/usr/bin/env bash

# mock pkg (audit) for simplemonitor

cat <<EOF
{
    "pkg_count": 1,
    "packages": {
        "curl": {
            "issue_count": 52,
            "issues": [
                {
                    "Affected versions": [
                        ">= 8.5.0 : < 8.14.0"
                    ],
                    "description": "curl -- Multiple vulnerabilities",
                    "cve": [
                        "CVE-2025-4947",
                        "CVE-2025-5025"
                    ],
                    "url": "https://vuxml.FreeBSD.org/freebsd/533b4470-3f25-11f0-b440-f02f7432cf97.html"
                },
			]
		}
	}
}
EOF
