#!/usr/bin/env bash

cat <<EOF
APC      : 001,031,0723
DATE     : 2018-02-06 10:44:07 -0500
HOSTNAME : some.host.name
VERSION  : 3.14.14 (31 May 2016) redhat
UPSNAME  : some.host.name
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2018-01-31 16:25:10 -0500
MODEL    :
STATUS   : ONLINE
LINEV    : 120.0 Volts
LOADPCT  : 49.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 8.6 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 3 Minutes
MAXTIME  : 0 Seconds
OUTPUTV  : 120.0 Volts
DWAKE    : 0 Seconds
LOTRANS  : 0.0 Volts
HITRANS  : 0.0 Volts
ALARMDEL : 30 Seconds
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
SELFTEST : ??
STATFLAG : 0x05000008
SERIALNO :
NOMINV   : 0 Volts
END APC  : 2018-02-06 10:44:40 -0500
EOF
