source 'https://rubygems.org'
gem 'github-pages', '>= 224'
gem 'rouge'
gem "jekyll", ">= 3.9.1"
gem "ffi", ">= 1.9.24"
gem "nokogiri", ">= 1.18.3"
gem "yajl-ruby", ">= 1.3.1"
gem "kramdown", ">= 2.5.1"
