source 'https://rubygems.org'
gem 'github-pages', '>= 229'
gem 'rouge'
gem "jekyll", ">= 3.9.4"
gem "ffi", ">= 1.9.24"
gem "nokogiri", ">= 1.8.5"
gem "yajl-ruby", ">= 1.3.1"
gem "kramdown", ">= 2.4.0"
