source 'https://rubygems.org'
gem 'github-pages', '>= 232'
gem 'rouge'
gem "jekyll", ">= 3.10.0"
gem "ffi", ">= 1.17.1"
gem "nokogiri", ">= 1.18.5"
gem "yajl-ruby", ">= 1.4.3"
gem "kramdown", ">= 2.4.0"
